# Generated by Django 3.2.6 on 2021-08-28 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('GET', 'method GET'), ('POST', 'method POST'), ('HEAD', 'method HEAD'), ('PUT', 'method PUT'), ('PATCH', 'method PATCH'), ('DELETE', 'method DELETE'), ('OPTIONS', 'method OPTIONS')], max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 8, 28, 16, 32, 12, 90923, tzinfo=utc))),
            ],
        ),
    ]
